### ISSUE TITLE
SOCKET_EXCEPTION Error while stablishing a connection.

### ISSUE THREAD

**Issue by eruecco87-zz** [obs-websocket-community-projects/obs-websocket-js#107]
### Description:

I'm using the web (not node) version of the javascript library. I'm establishing the connection like explained in the readme file

```
<!-- Socket -->
<script src="js/libraries/obs-websocket.min.js"></script>
<script>
    var socket = new OBSWebSocket();
    socket.connect({ address: 'localhost:4444', password: 'password' });
</script>
```
But I keep getting this error after the connection is attempted.

```
code: "SOCKET_EXCEPTION"
description: "An exception occurred from the underlying WebSocket."
error: "An exception occurred from the underlying WebSocket."
status: "error"
```

### Versions Used:
  - obs-websocket-js version: v1.2.0
  - obs-websocket plugin version: v4.3.2
  - obs-studio version: v21.1.1

**Comment by Lange** [comment]
@eruecco87 Are you still encountering this?
