### ISSUE TITLE
on "Exiting" isn't Triggered

### ISSUE THREAD

**Issue by Pckool** [obs-websocket-community-projects/obs-websocket-js#137]
### Description:
 I'm trying to have an action occur on OBS exiting. But unfortunately it seems to never be triggered and I can't seem to force it to trigger. 

### Sample Code
```
obs.on('Exiting', () =>{
    console.log('OBS Is Exiting...');
    disconnectOBS();
});
```
Issue: the log never occurs, meaning the event is never triggered.

### Versions Used:
  - obs-websocket-js version: release: v2.0.1
  - obs-websocket plugin version: 4.5.0
  - obs-studio version: Latest 23.0.1

**Comment by Lange** [comment]
It's possible that this is an issue in `obs-websocket` itself, and not in `obs-websocket-js`. Have you been able to verify if the message is being sent at all? You may want to open an issue on `obs-websocket` as well.

**Comment by Pckool** [comment]
Good call. I'll check to see if the message is being sent by `obs-websocket`.

**Comment by artdevgame** [comment]
@Pckool I know this is pretty old now, but did you get to the bottom of this? I'm experiencing the same issue.

**Comment by artdevgame** [comment]
I can see the event in my OBS logs:

```
16:24:42.887: ==== Shutting down ==================================================
16:24:43.266: [obs-websocket] Update << '{
16:24:43.266:     "update-type": "Exiting"
16:24:43.266: }'
```
