### ISSUE TITLE
Permit arbitrary websocket URLs

### ISSUE THREAD

**Issue by tikatoo** [obs-websocket-community-projects/obs-websocket-js#195]
For those of us placing the OBS websocket server behind a proxy, this is kind of necessary.

For myself specifically, because of Reasons\*, I can only use HTTPS to connect from my client. Running a proxy isn't difficult, but the current API of this package makes it difficult (to put it mildly) to actually establish a secure websocket connection.

> \* For completeness: my client runs in the browser, and due to limitations in my hosting service the page is forced to use HTTPS. Browsers will therefore prevent unsecured connections (yes, even connections that _would_ be upgraded to HTTPS).

I feel like allowing any websocket URL while we're at it would be logical, to support a wider range of potential use cases (whatever those may be).

**Comment by Niek** [comment]
I have a fix for your usecase in https://github.com/haganbmj/obs-websocket-js/pull/201
