### ISSUE TITLE
How to utilize obs-websocket 4.9.0 new events.

### ISSUE THREAD

**Issue by samcreate** [obs-websocket-community-projects/obs-websocket-js#224]
### Description:
obs-websocket has some very handy new events on media sources. Such as ["MediaEnded"](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#mediaended)

This doesn't work:

`obs.on("MediaStarted", (e) => {
	console.log("MediaStarted!", e);
  });`

It also mentions that "These events are emitted by the OBS sources themselves" but looks like sources are just plain js objects when retrieving them with `obs.send("GetSceneList")`

### Versions Used (if applicable):
  - obs-websocket-js version: 4.0.2
  - obs-websocket plugin version: 4.9.0
  - obs-studio version: 24.0.6
  - node version: 12.13.1

**Comment by zoton2** [comment]
I tested attaching it directly to the OBS connection and it works fine. The documentation seems to be worded weirdly; there's no way something sent over WebSocket would ever be able to output events of it's own (unless I'm mistaken).

As the release notes for 4.9.0 mention, "Only use this release with OBS Studio 26.1 or above!" so you may want to update your OBS version.

**Comment by hodbauer** [comment]
Hi,
I have a similar issue about the `d.ts` of this version.

I call `obs.send('GetRecordingStatus') ...`
And it return the expected value, but i've got typescript error that this event not exist.

The `GetRecordingStatus` event is part of 4.9.0 so it should not do this error.

**Comment by zoton2** [comment]
Yeah the typings haven't been updated in a while, it was annoying to me too. I fixed some issues with them on my own fork and still need to make a PR, and then it'd need to be updated on npm too.

**Comment by samcreate** [comment]
@zoton2 Could you share what it looks like to attaching it directly to the OBS connection?

**Comment by zoton2** [comment]
I was just using it like normal events. So like...
```javascript
obs.on('MediaStarted', (data) => {
  /* data returned here */
});
```
Again, make sure your `obs-studio` version is up to date.

**Comment by Panger95** [comment]
This issue seems to be because the obs-studio is not using version 26.1 or above.
