### ISSUE TITLE
Update typings for obs-websocket 4.9.x

### ISSUE THREAD

**Issue by Trezub** [obs-websocket-community-projects/obs-websocket-js#257]
### Description:
The typings seems to be outdated on npm.
I was able to compile the typings locally and use new events like `VirtualCamStopped` etc but with the package downloaded from npm, the new events and requests from the v4.9.x are missing.

### Versions Used (if applicable):
  - obs-websocket-js version: 4.0.2
  - obs-websocket plugin version: 4.9.1
  - obs-studio version:
  - node version:

**Comment by zoton2** [comment]
I mentioned this in Discord, with my edited script that was merged recently it should need regenerating and then a new NPM version publishing, but I don't think I have access to do that myself.

**Comment by jdeng89** [comment]
Given that there is going to be quite a number of updates necessary to support >5.0.0, I think it would be wise to tag / update npm now. I was able to build locally without issue and use the new typings so unless there are any other issues I think this would be very helpful to get published soon.
