### ISSUE TITLE
OBSWebSocket is not a constructor

### ISSUE THREAD

**Issue by slashinfty** [obs-websocket-community-projects/obs-websocket-js#267]
### Description:
I keep getting `Uncaught TypeError: OBSWebSocket is not a constructor`.

My code for it is
```js
const { OBSWebSocket } = require('obs-websocket-js');
const obs = new OBSWebSocket();
```

### Versions Used (if applicable):
  - obs-websocket-js version: 4.0.3
  - obs-websocket plugin version: 4.9.1
  - obs-studio version: 27.0.1
  - node version: 14.17.6

**Comment by slashinfty** [comment]
Did not looked at v4 documentation, which requires
```js
const OBSWebSocket = require('obs-websocket-js')
```

**Comment by faraamcode** [comment]
This same thing happen to me while trying to use it with nestjs but I solved it

```
import  *  as OBSWebSocket  from  'obs-websocket-js'

const obs = new OBSWebsocket()

```
