### ISSUE TITLE
Bug: GetGroupSceneItemList and GetSceneItemList returns scene items in reverse

### ISSUE THREAD

**Issue by majorofxd** [obs-websocket-community-projects/obs-websocket-js#288]
### Description:
Calling 'GetSceneItemList' would yield the list of scene items ("Sources" in OBS GUI) in reverse order, that is, from bottom to top.

Same issues arise when calling "GetSceneList", where scenes are listed from bottom to top.

I am expecting that the scene items will be returned from top to bottom, that is, the order they were as listed in the OBS GUI.

Also notified obsproject/obs-websocket github in case such issue is from their side.

### Versions Used (if applicable):
  - obs-websocket-js version: v5.0.0-beta.2
  - obs-websocket plugin version: 5.0.0-beta1
  - obs-studio version: 27.2.4
  - os: Windows 10 Home Single Language Version 21H2

**Comment by t2t2** [comment]
Data is returned as-is from obs-websocket so yeah closing in favor of obsproject/obs-websocket#955
