### ISSUE TITLE
RefreshBrowserSource gone?

### ISSUE THREAD

**Issue by rodrigograca31** [obs-websocket-community-projects/obs-websocket-js#304]
### Description:

previously (4.9.....) I had `obs.send("RefreshBrowserSource", { sourceName: "streamelements" });` to reload my browsers when they bugged sometimes...

5.x doesnt seem to have that event.... How do we go about it?
Toggeling its visibility seems to work...
but as I explained in #303 it requires lots of code... we go from 1 line to 20 lines of code:

```js
obs.call("GetSceneItemId", {
	sceneName: "browsers",
	sourceName: "streamelements",
})
.then((data) => {
	console.log(data.sceneItemId);
	obs.call("SetSceneItemEnabled", {
		sceneName: "browsers",
		sceneItemId: data.sceneItemId,
		sceneItemEnabled: false,
	})
	.then(() => {
		obs.call("SetSceneItemEnabled", {
			sceneName: "browsers",
			sceneItemId: data.sceneItemId,
			sceneItemEnabled: true,
		});
	});
});
```

This feature was basically access to that last button `Refresh cache of current page`
![image](https://user-images.githubusercontent.com/1134310/188293531-7f475e1f-dc97-4179-a0e6-f377416949d9.png)

### Versions Used (if applicable):
  - obs-websocket-js version: obs-websocket-js@5.0.1
  - obs-websocket plugin version: none
  - obs-studio version: OBS Studio - 28.0.1 (linux)
  - node version: v17.9.1

**Comment by t2t2** [comment]
https://github.com/obsproject/obs-websocket/issues/972
