### ISSUE TITLE
CommonJS imports with Node16 ModuleResolutions broken

### ISSUE THREAD

**Issue by luuktap** [obs-websocket-community-projects/obs-websocket-js#355]
### Description:
Package resolution is broken in a TypeScript project using CommonJS with Module and ModuleResolution set to `Node16`.
Also see: https://arethetypeswrong.github.io/?p=obs-websocket-js%405.0.5 => node16 (from CJS).
This breaks importing completely. 

Any import will get the following TypeScript error: `The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'.`

If I don't specify any export (just `import OBSWebSocket from "obs-websocket-js";`), an additional TypeError is thrown at runtime: `OBSWebSocket is not a constructor`. Manually specifying `/json` or `/msgpack` gets rid of this. The other error remains.

### Versions Used (if applicable):
  - obs-websocket-js version: 5.0.5
  - obs-websocket plugin version:
  - obs-studio version:
  - node version:

**Comment by NotBlue-Dev** [comment]
up

**Comment by t2t2** [comment]
Updated tooling, [now shows as good](https://arethetypeswrong.github.io/?p=obs-websocket-js%405.0.6)

Also made `OBSWebSocket` available as a named export
